In [1]:
import torch

# How to create a tensor object

# 1-D array

In [2]:
sample = torch.tensor([10,11])
sample.shape

torch.Size([2])

# As soon as the bracket ends, bring the numbers to the bottom

In [3]:
x = torch.tensor([[10,11],[1,2]])
x.shape

torch.Size([2, 2])

## [10,11
## 1,2]

In [4]:
y = torch.tensor([[10],[11]])
y.shape

torch.Size([2, 1])

# [10
# 11]

# The code below would help you visualize a 3-D tensor better, where "a" is a 3 dimensional tensor


In [5]:
import torch
import plotly.graph_objs as go
import plotly.offline as pyo

# Create a 3-dimensional tensor
a = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Create a list of all the x, y, and z values in the tensor
x_vals = []
y_vals = []
z_vals = []
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
            x_vals.append(i)
            y_vals.append(j)
            z_vals.append(k)

# Create a Plotly 3D scatter plot
trace = go.Scatter3d(
    x=x_vals,
    y=y_vals,
    z=z_vals,
    mode='markers',
    marker=dict(
        size=5,
        color=a.flatten(),
        colorscale='Viridis',
        opacity=0.8
    )
)

# Create the plot layout
layout = go.Layout(
    margin=dict(l=0, r=0, b=0, t=0),
    scene=dict(
        xaxis=dict(title='Dimension 1'),
        yaxis=dict(title='Dimension 2'),
        zaxis=dict(title='Dimension 3')
    )
)

# Combine the trace and layout into a figure and display it
fig = go.Figure(data=[trace], layout=layout)
pyo.plot(fig, filename='tensor.html')


'tensor.html'

# Tensor with Random Numbers

torch.zeros((shape tuple))

In [6]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[9, 1, 7, 8],
        [0, 3, 4, 2],
        [6, 8, 1, 0]])

In [9]:
torch.randint(low=0, high=10, size=(3,4,2))

tensor([[[8, 1],
         [5, 7],
         [1, 1],
         [6, 5]],

        [[2, 4],
         [4, 2],
         [4, 6],
         [6, 5]],

        [[3, 4],
         [6, 5],
         [4, 3],
         [4, 9]]])

In [ ]:
torch.randint(low=0, high=10, size=(3,4,4))

tensor([[[0, 5, 5, 2],
         [8, 9, 8, 9],
         [8, 7, 1, 9],
         [6, 4, 5, 0]],

        [[8, 5, 0, 0],
         [5, 0, 1, 4],
         [2, 1, 8, 9],
         [0, 6, 3, 3]],

        [[2, 0, 8, 5],
         [5, 4, 5, 6],
         [2, 1, 3, 5],
         [9, 3, 0, 3]]])

[0117/004617.287746:ERROR:file_io_posix.cc(153)] open /home/gabrielspacki/.config/BraveSoftware/Brave-Browser/Crash Reports/pending/557eed16-450e-4ac0-8b03-84426dd6ec27.lock: File exists (17)


Abrindo em uma sessão de navegador existente.


# From above tensor we can see that size is in the form of (Number of stacks (channels in images, will be covered in the future lessons), rows, columns)

# Think of a cuboid while trying to visualize this tensor

Source: https://www.researchgate.net/publication/357820593/figure/fig2/AS:1134626982625284@1647527561324/A-3D-tensor-of-a-Red-Green-Blue-RGB-image-of-a-dimension-of-4-A-4-A-3.png

![3-D Tensor](https://www.researchgate.net/publication/357820593/figure/fig2/AS:1134626982625284@1647527561324/A-3D-tensor-of-a-Red-Green-Blue-RGB-image-of-a-dimension-of-4-A-4-A-3.png)