In [1]:
import torch

# Multiplication

In [19]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]]) 

In [3]:
print(x.shape)

torch.Size([2, 4])


In [4]:
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

# Sum

In [5]:
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

# Reshape

## There are multiple ways to reshape a tensor

## 1) view

In [6]:
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [7]:
x.shape

torch.Size([2, 4])

In [8]:
x.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

## While Reshaping, we need to keep in mind that the number of elements inside the tensor should remain the same, like in the above example we had 8 elements in total, the possible shapes to which it can be converted should have 8 elements

In [9]:
x.view(8,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

## 2) Squeeze

## In squeeze, we provide the axis index that we want to remove which has only 1 item in that dimension

In [10]:
a = torch.ones(2,1,10)

In [11]:
# This is a tensor of 2 "stacks" having one row and 10 columns each, total 20 elements
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [12]:
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.squeeze(1)
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 1, 10])
This is the shape after squeezing torch.Size([2, 10])


## As you can see we removed the first axis index which only had 1 item. If the axis has more than one item, it won't be removed

In [13]:
a = torch.ones(2,2,10)
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.squeeze(1)
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 2, 10])
This is the shape after squeezing torch.Size([2, 2, 10])


In [14]:
a = torch.ones(2,3,1)
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.squeeze(2)
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 3, 1])
This is the shape after squeezing torch.Size([2, 3])


## 3) Unsqueeze

## It is the exact opposite of squeeze, where instead of removing, we are adding a dimension to our tensor

In [15]:
a = torch.ones(2,3)
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.unsqueeze(2)
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 3])
This is the shape after squeezing torch.Size([2, 3, 1])


## [None] indexing: A very common approach

In [16]:
a = torch.ones(2,3)

In [17]:
# Adding none would auto create a fae dimension at the specified axis
print(a[None].shape) # Fake axis at 0 index
print(a[:,None].shape) # Fake axis at 1 index
print(a[:,:,None].shape) # Fake axis at 2 index

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


# In computer vision, keep in mind that the shape of tensor would be:

## (total number of elements) for 1-D tensor
## (rows,columns) for 2-D tensor
## (number of channels, rows, columns) for 3-D tensor
## (batch size, num of channels, rows, columns) for 4-D tensor

## In future lectures you would see how rows and columns turn into height and width of the image giving us (batch size, num channels, height, width) tensors